{% set version = "1.8.1" %}

package:
  name: ardap
  version: {{ version }}

source:
  url: https://github.com/dsarov/ardap/archive/v{{ version }}.tar.gz # [linux64,linux32]

build:
  number: 0

requirements:
  build:
      - {{ compiler('cxx') }}
  host:
      - art
      - trimmomatic
      - bwa
      - bedtools=2.28.0
      - seqtk
      - pindel
      - mosdepth
      - samtools=1.9
      - picard
      - gatk4=4.1.8
      - sqlite
      - snpEff=4.3.1t
      - nextflow
      - fasttree
      - delly
      - bcftools
  run:
      - trimmomatic
      - bwa
      - bedtools=2.28.0
      - seqtk
      - pindel
      - mosdepth
      - samtools=1.9
      - picard
      - gatk4=4.1.8
      - sqlite
      - snpEff=4.3.1t
      - nextflow
      - fasttree
      - delly
      - bcftools

test:
  commands:
      - nextflow -h

about:
  home: 'https://github.com/dsarov/ardap'
  license: MIT
  license_file: LICENSE
  summary: 'Comprehensive resistance detection from WGS'

